spring.application.name=modoaviao-backend
spring.profiles.active=dev

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/modoaviao
spring.datasource.username=postgres
spring.datasource.password=200814
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=FUCxYQXcjyMgJuEJ2jGDn1XZ7S7f9/jJz/6Qw+y1Ac8=
app.jwt.expiration-ms=86400000


app.cors.allowed-origins=http://localhost:5173,http://localhost:8081,http://localhost:8083